// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYWvIJWWwqu55xGoRjJEtm9Oy0bmuewdQ',
    appId: '1:148955198726:web:bc1a1db9e989bdc6051a87',
    messagingSenderId: '148955198726',
    projectId: 'inventorypro-40935',
    authDomain: 'inventorypro-40935.firebaseapp.com',
    storageBucket: 'inventorypro-40935.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD5LDLj22NdXGvlT9Z4L5PSk4-v9CJ7Ps',
    appId: '1:148955198726:android:a059e120a262db6b051a87',
    messagingSenderId: '148955198726',
    projectId: 'inventorypro-40935',
    storageBucket: 'inventorypro-40935.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ_C0ILyZl-HifOEgongAq8CTO-zR6gKk',
    appId: '1:148955198726:ios:f94577e5e66dd4eb051a87',
    messagingSenderId: '148955198726',
    projectId: 'inventorypro-40935',
    storageBucket: 'inventorypro-40935.firebasestorage.app',
    iosBundleId: 'com.example.inventoryPro',
  );
}
